development:
  adapter: postgresql
  encoding: unicode
  database: TopEd_development
  host: localhost
  pool: 5
  username: postgres
  password: 2112

test:
  adapter: postgresql
  encoding: unicode
  database: TopEd_test
  host: localhost
  pool: 5
  username: postgres
  password: 2112

production:
  encoding: utf8
  pool: 15